[allowlist]
  description = "Global Allowlist"
        
  # Ignore based on any subset of the line
  regexes = [
    # Ignore lines containing netflix:netflix
    '''netflix:netflix''',
    # Ignore lines containing pagila:pagila
    '''pagila:pagila''',
  ]